### ISSUE TITLE
BLE Explorer Sample Droid App Crash

### ISSUE THREAD

**Issue by partialdata** [xamarin/Monkey.Robotics#46]
Trying to run the BLE Explorer Sample app droid on Samsung Galaxy Tablet  GT-P5210  

Android API is 17  I am getting this when deploying to the hardware. The app loads on the device then fails and i receive the following in Xamarin Studio.

Java.Lang.RuntimeException: Unable to start activity ComponentInfo{Robotics.Mobile.BtLEExplorer.Droid/md559bf29f023ca5abe850fc269ea256505.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "md5023215d593d44f50438f36261234faca.Adapter" on path: /data/app/Robotics.Mobile.BtLEExplorer.Droid-1.apk
  at --- End of managed exception stack trace ---
  at java.lang.RuntimeException: Unable to start activity ComponentInfo{Robotics.Mobile.BtLEExplorer.Droid/md559bf29f023ca5abe850fc269ea256505.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "md5023215d593d44f50438f36261234faca.Adapter" on path: /data/app/Robotics.Mobile.BtLEExplorer.Droid-1.apk
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245)
  at at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
  at at android.app.ActivityThread.access$700(ActivityThread.java:150)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
  at at android.os.Handler.dispatchMessage(Handler.java:99)
  at at android.os.Looper.loop(Looper.java:176)
  at at android.app.ActivityThread.main(ActivityThread.java:5279)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:511)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
  at at dalvik.system.NativeStart.main(Native Method)
  at Caused by: java.lang.ClassNotFoundException: Didn't find class "md5023215d593d44f50438f36261234faca.Adapter" on path: /data/app/Robotics.Mobile.BtLEExplorer.Droid-1.apk
  at at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
  at at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
  at at md559bf29f023ca5abe850fc269ea256505.MainActivity.n_onCreate(Native Method)
  at at md559bf29f023ca5abe850fc269ea256505.MainActivity.onCreate(MainActivity.java:28)
  at at android.app.Activity.performCreate(Activity.java:5267)
  at at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
  at at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
  at ... 11 more

**Comment by parkerhillius** [comment]
I'm getting the same exception when deploying my app to a Motorola DROID RAZR (API 16). It appears the exception is happening when I create the adapter: new Robotics.Mobile.Core.Bluetooth.LE.Adapter(). Have you found a solution or workaround?

**Comment by Nfear** [comment]
I am getting the same error on my Huawei y300 with API 16.

Might it be because BLE was introduced in Android 4.1 (API 18)?

**Comment by parkerhillius** [comment]
Yes it was - we ended up targeting a minimum API of 18.
